server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user-db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation:true
    properties:
      hibernate:
        show_sql: true
    output:
      ansi:
        enabled: always
  kafka:
    bootstrap-servers: localhost:29092


  # Log Level of Application
logging:
  level:
    com.pinhobrunodev: TRACE
    root: INFO # More details but not of Everything
    org.springframework.web: DEBUG # Log to see into the Requests
    org.hibernate: INFO  # Log to see the Hibernate
